version: '3'
services:
  fastapi:
    build: app
  ports:
    - "8000:8000"
  db:
    image: "postgres:13.4"
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data